services:
  postgres:
    image: postgres:16
    container_name: liquidacao_db
    environment:
      POSTGRES_USER: liquidacao_user
      POSTGRES_PASSWORD: liquidacao_pass
      POSTGRES_DB: liquidacao_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: